general:
  startdate: 1980-01-01
  enddate: null

dbserver:
  uid: titus
  pwd: VDYCDuayE4ckRMcXbNcxWXkjDujABkTd2WyFZJc8HzZazd4rZN4K3SDyw3FrfBep2Gbae6c7nnMgaans6bKvQFxAbMuenjf3crPcM9ktaURrH273EG3CQC4dA
  host: apollo.c7rp7exuh1rh.us-east-2.rds.amazonaws.com
  port: 5432